data_local: /dev/shm/mjobanputra/oscar_de_mds_loader
data_remote: /mnt/lustre/meurers/mjobanputra60/oscar_de_mds
max_seq_len: 2048
global_seed: 17

# Run Name
run_name: mpt-100m-2B-wq-de-triton # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 768
  n_heads: 12
  n_layers: 12
  expansion_ratio: 4
  max_seq_len: ${max_seq_len}
  vocab_size: 20000
  attn_config:
    attn_impl: triton
    alibi: true

# Tokenizer
tokenizer:
  name: /mnt/lustre/meurers/mjobanputra60/tokenizers/de_vocab.json
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    keep_zip: false
    cache_limit: 450gb
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    shuffle: false
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    keep_zip: false
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 2000ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 1.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 40000ba # ~ 2.0B tokens
eval_interval: 2000ba
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 512

# System
seed: ${global_seed}
device_eval_batch_size: 32
# device_train_microbatch_size: 16
device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 5ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  wandb:
    entity: notsomonk
    project: thesis
    name: ${run_name}
    init_kwargs:
      id: hgt59ms5
      resume: must

allow_wandb_val_change: true

# Checkpoint to local filesystem or remote object store
save_interval: 5000ba
save_num_checkpoints_to_keep: 16  # Important, this cleans up checkpoints saved to DISK
save_folder: /mnt/lustre/meurers/mjobanputra60/models/${run_name}/checkpoints
#save_overwrite: true
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

autoresume: true
# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt
